const Data = [
	{
		id: 1,
		Name: "iphone 15 promax",
		price: "1199",
		image: "Image/product_1.jpg",
		category: "phone",
		type: "featured",
	},
	{
		id: 2,
		Name: "series 9 ultra",
		price: "96",
		image: "Image/product_2.jpg",
		category: "watch",
		type: "new",
	},
	{
		id: 3,
		Name: "Wool pullover",
		price: "119",
		image: "Image/product_3.jpg",
		category: "fashion",
		type: "top",
	},
	{
		id: 4,
		Name: "laptop hp",
		price: "422.99",
		image: "Image/product_4.jpg",
		category: "laptop",
		type: "featured",
	},
	{
		id: 5,
		Name: "iphone 13",
		price: "1099",
		image: "Image/product_5.jpg", //
		category: "phone",
		type: "new",
	},
	{
		id: 6,
		Name: "projector",
		price: "19",
		image: "Image/product_6.jpg",
		category: "electronics",
		type: "top",
	},
	{
		id: 7,
		Name: "samsung ultra 24",
		price: "949",
		image: "Image/product_7.jpg",
		category: "phone",
		type: "featured",
	},
	{
		id: 8,
		Name: "sweet pants",
		price: "189",
		image: "Image/product_8.jpg",
		category: "fashion",
		type: "new",
	},
	{
		id: 9,
		Name: "headphone plus",
		price: "67",
		image: "Image/product_9.jpg",
		category: "headphone",
		type: "top",
	},
	{
		id: 10,
		Name: "acer laptop",
		price: "3999",
		image: "Image/product_10.jpg",
		category: "laptop",
		type: "featured",
	},
	{
		id: 11,
		Name: "gold watch",
		price: "49",
		image: "Image/product_11.jpg",
		category: "watch",
		type: "new",
	},
	{
		id: 12,
		Name: "hp headphone",
		price: "79",
		image: "Image/product_12.jpg",
		category: "headphone",
		type: "top",
	},
	{
		id: 13,
		Name: "smart tv",
		price: "1,534",
		image: "Image/product_13.jpg",
		category: "electronics",
		type: "featured",
	},
	{
		id: 14,
		Name: "mac book",
		price: "5999",
		image: "Image/product_14.jpg",
		category: "laptop",
		type: "new",
	},
	{
		id: 15,
		Name: "power bank",
		price: "94",
		image: "Image/product_15.jpg",
		category: "electronics",
		type: "top",
	},
	{
		id: 16,
		Name: "realme c63",
		price: "599",
		image: "Image/product_16.jpg",
		category: "phone",
		type: "featured",
	},
	{
		id: 17,
		Name: "adidas samba",
		price: "134",
		image: "Image/product_17.jpg",
		category: "fashion",
		type: "new",
	},
	{
		id: 18,
		Name: "classic watch",
		price: "95",
		image: "Image/product_18.jpg",
		category: "watch",
		type: "top",
	},
	{
		id: 19,
		Name: "oppo ",
		price: "143",
		image: "Image/product_19.jpg",
		category: "phone",
		type: "featured",
	},
	{
		id: 20,
		Name: "teddy bear",
		price: "34",
		image: "Image/product_20.jpg",
		category: "toys",
		type: "new",
	},
	{
		id: 21,
		Name: "jacket",
		price: "74",
		image: "Image/product_21.jpg",
		category: "fashion",
		type: "top",
	},
	{
		id: 22,
		Name: "t-shirt baby",
		price: "34",
		image: "Image/product_22.jpg",
		category: "fashion",
		type: "featured",
	},
	{
		id: 23,
		Name: "men watch",
		price: "144",
		image: "Image/product_23.jpg",
		category: "watch",
		type: "new",
	},
	{
		id: 24,
		Name: "wireless",
		price: "184",
		image: "Image/product_24.jpg",
		category: "electronics",
		type: "top",
	},
	{
		id: 25,
		Name: "ear pods 3",
		price: "44",
		image: "Image/product_25.jpg",
		category: "headphone",
		type: "featured",
	},
	{
		id: 26,
		Name: "speaker",
		price: "99",
		image: "Image/product_26.jpg",
		category: "electronics",
		type: "new",
	},
	{
		id: 27,
		Name: "baby toys",
		price: "14",
		image: "Image/product_27.jpg",
		category: "toys",
		type: "top",
	},
	{
		id: 28,
		Name: "vivo laptop",
		price: "2995",
		image: "Image/product_28.jpg",
		category: "laptop",
		type: "featured",
	},
	{
		id: 29,
		Name: "smart watch",
		price: "143",
		image: "Image/product_29.jpg",
		category: "watch",
		type: "new",
	},
	{
		id: 30,
		Name: "samsung galaxy ",
		price: "3849",
		image: "Image/product_30.jpg",
		category: "laptop",
		type: "top",
	},
	{
		id: 31,
		Name: "scoter",
		price: "574",
		image: "Image/product_31.jpg",
		category: "toys",
		type: "featured",
	},
	{
		id: 32,
		Name: "camera",
		price: "124",
		image: "Image/product_32.jpg",
		category: "toys",
		type: "new",
	},
	{
		id: 33,
		Name: "car ",
		price: "194",
		image: "Image/product_33.jpg",
		category: "toys",
		type: "top",
	},
	{
		id: 34,
		Name: "ear pods 2",
		price: "84",
		image: "Image/product_34.jpg",
		category: "headphone",
		type: "featured",
	},
	{
		id: 35,
		Name: "Wired earphone",
		price: "44",
		image: "Image/product_35.jpg",
		category: "headphone",
		type: "new",
	},
];
export default Data;
